name: Renovate

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC role assumption
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::819004394028:role/github-ecr-renovate
          aws-region: us-east-1

      - name: Logout old Docker credentials
        run: docker logout 819004394028.dkr.ecr.us-east-1.amazonaws.com || true

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
          | docker login \
            --username AWS \
            --password-stdin 819004394028.dkr.ecr.us-east-1.amazonaws.com

      - name: Run Renovate
        uses: renovatebot/github-action@v46.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          AWS_REGION: us-east-1
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: debug
          DOCKER_CONFIG: /home/runner/.docker
