name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 3 AM UTC
  push:                  # Runs on every push to any branch

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: renovatebot/github-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
